name: check
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  test:
    name: ${{ matrix.py }}
    runs-on: Ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
        - 3.8
        - 3.7
        - 3.6
        - pypy2
        - pypy3

    steps:
    - uses: actions/checkout@v2
    - name: setup python for tox
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install tox
      run: python -m pip install tox
    - name: setup python for test ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: setup test suite for ${{ matrix.os }}-${{ matrix.py }}
      run: tox -vve py --notest
    - name: run test suite for ${{ matrix.os }}-${{ matrix.py }}
      run: tox -e py

  check:
    name: check ${{ matrix.tox_env }}
    runs-on: Ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
        - package_description
        - docs

    steps:
    - uses: actions/checkout@v2
    - name: setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install tox
      run: python -m pip install tox
    - name: run check for ${{ matrix.tox_env }}
      run: python -m tox -e ${{ matrix.tox_env }}

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [check, test, lint]
    runs-on: ubuntu-latest
    steps:
    - name: setup python to build package
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install pep517
      run: python -m pip install pep517
    - uses: actions/checkout@v2
    - name: build package
      run: python -m pep517.build -s -b . -o dist
    - name: publish to PyPi
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.pypi_password }}
